{
 "title": "SABD - Q2 Aeroporti con ritardi in partenza significativi (real-time)",
 "tags": [
  "sabd",
  "q2"
 ],
 "time": { "from": "2025-01-01T00:00:00.000Z", "to": "2025-05-01T00:00:00.000Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Voli con ritardo grave (>30 min) nel tempo - finestra 1h (per aeroporto in top-10)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"flights\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"_measurement\"] == \"q2_1h\" and r[\"_field\"] == \"severe_delays\") |> keep(columns: [\"_time\", \"_value\", \"origin_airport_id\"]) |> group(columns: [\"origin_airport_id\"]) |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Ritardo medio in partenza - finestra 1h (per aeroporto in top-10)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "from(bucket: \"flights\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"_measurement\"] == \"q2_1h\" and r[\"_field\"] == \"dep_delay_mean\") |> keep(columns: [\"_time\", \"_value\", \"origin_airport_id\"]) |> group(columns: [\"origin_airport_id\"]) |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Voli con ritardo grave (>30 min) nel tempo - finestra 6h (per aeroporto in top-10)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"flights\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"_measurement\"] == \"q2_6h\" and r[\"_field\"] == \"severe_delays\") |> keep(columns: [\"_time\", \"_value\", \"origin_airport_id\"]) |> group(columns: [\"origin_airport_id\"]) |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Top-10 aeroporti dall'inizio del dataset - global (si popola al termine del replay)",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"flights\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r[\"_measurement\"] == \"q2_global\") |> filter(fn: (r) => r[\"_field\"] == \"num_flights\" or r[\"_field\"] == \"severe_delays\" or r[\"_field\"] == \"dep_delay_mean\" or r[\"_field\"] == \"dep_delay_max\") |> last() |> keep(columns: [\"airport_rank\", \"origin_airport_id\", \"_field\", \"_value\"]) |> group() |> pivot(rowKey: [\"airport_rank\", \"origin_airport_id\"], columnKey: [\"_field\"], valueColumn: \"_value\") |> map(fn: (r) => ({ r with airport_rank: int(v: r.airport_rank), origin_airport_id: int(v: r.origin_airport_id) })) |> sort(columns: [\"airport_rank\"])"
    }
   ]
  }
 ]
}